# Configuration file for mdbook

[book]
authors = ["Petteri Aimonen"]
language = "en"
src = "."
title = "Nanopb Documentation"
description = "Nanopb is a C library for encoding and decoding messages in Google's Protocol Buffers format with minimal requirements for RAM and code space."

[build]
build-dir = "../build/mdbook"

[output.html]
sidebar-header-nav = true
git-repository-url = "https://github.com/nanopb/nanopb"

[preprocessor.permalinks]
#optional = true # Doesn't work, https://github.com/tonywu6/mdbookkit/issues/24
